### PR TITLE
BUG: check loops in remove_false_nodes against any node degree

### PR DESCRIPTION
**Pull request by martinfleis**

### CODE REVIEW

**Comment by martinfleis** [comment]
@jGaboardi if you want to ask about tests, I really don't want to do them :D

**Comment by jGaboardi** [comment]
Do we not need a test for this? Or is the test implicit?

**Comment by jGaboardi** [comment]
> @jGaboardi if you want to ask about tests, I really don't want to do them :D

perfect timing -- we commented at exactly the same time

**Comment by martinfleis** [comment]
It is not implicit but given how tests for this are structured now, we would need to alter the test data. Just pretend you missed the missing tests :D

**Review by jGaboardi — APPROVED** [review]

**Pull request merged**
