### PR TITLE
pytest-xdist for multicore CI

### PR DESCRIPTION
**Pull request by jGaboardi**
xref: pysal/spopt#211, pysal/spaghetti#661

### CODE REVIEW

**Comment by jGaboardi** [comment]
[Failures](https://github.com/pysal/momepy/runs/4835325249?check_suite_focus=true#step:6:244) all have acceptable tolerances. However, this seems to be be the first time they cropped up. Wondering is lack of precision to do with multicore schema.

**Comment by martinfleis** [comment]
Can you wrap the affected tests in `pytest.approx`? We have done it elsewhere as well.

**Comment by jGaboardi** [comment]
@martinfleis All precision failures are now addressed.

**Comment by martinfleis** [comment]
Thanks!

**Pull request merged**
