### PR TITLE
resolves bug in Percentiles append.

### LINKED ISSUE #426: bug in Percentiles append
One note aside - we have a bug in Percentiles as well. This should be the same as line 898 https://github.com/pysal/momepy/blob/c574bcfd8445dc8b5e54912cd8fe28ea10ff2cf5/momepy/diversity.py#L925

_Originally posted by @martinfleis in https://github.com/pysal/momepy/issues/423#issuecomment-1254168703_

### PR DESCRIPTION
**Pull request by jGaboardi**
Resolves #426.

### CODE REVIEW

**Comment by martinfleis** [comment]
We should probably test this somehow.

**Comment by jGaboardi** [comment]
> We should probably test this somehow.

I've added two tests (one unweighted and one weighted) to check for correct behavior.

**Comment by jGaboardi** [comment]
xref #423 Interesting that now `py38` tests are passing here where `py39`, etc. fail. The only major difference that I found is [`numpy=1.21.6`](https://github.com/pysal/momepy/actions/runs/3102334399/jobs/5024541151#step:5:161) vs. [`numpy=1.23.3`](https://github.com/pysal/momepy/actions/runs/3102334399/jobs/5024541264#step:5:162). Seems at least possibly related to the weird [`numpy.argsort` behavior](https://github.com/geopandas/geopandas/issues/2558#issuecomment-1254325817) that @jorisvandenbossche found deep in `pandas`?

**Comment by jGaboardi** [comment]
xref https://github.com/pandas-dev/pandas/pull/48711

**Comment by jGaboardi** [comment]
@martinfleis Anything more you think should be done for this?

**Review by martinfleis — APPROVED** [review]
I was hoping to see the green ci but given pandas release may not come soon, let's merge.

I am thinking we should do a patch release that changes our requirements to avoid ppl running into that bug...

**Pull request merged**
