### PR TITLE
Allow nodes as an input to graph construction method 'gdf_to_nx'

### PR DESCRIPTION
**Pull request by leigh-pozibl**
Added option to input node features to the method gdf_to_nx

### CODE REVIEW

**Comment by martinfleis** [comment]
Hey @leigh-pozibl was this all intentional? Is this something you'd like to see in?

**Comment by leigh-pozibl** [comment]
Hi Martin,

sorry, I inadvertently published that pull request (I'm new to github!)

I have been trying out momepy and wanted to get some data attached to the
nodes in a generated graph. That is useful to me but not sure if that is
something you guys have considered?

apologies for the error.

regards
Leigh

**Comment by martinfleis** [comment]
If you already have nodes and edges, you can create a graph directly using networkx. The purpose of this function is to create a graph from LineString geometry only.

**Comment by leigh-pozibl** [comment]
sure, I liked how your function could build the graph from geometries
though which is my use case.  Is there any particular reason why you don't
consider Point geoms as an input as well? Am I missing something?

For context, I am building graphs of electrical grids, and model the poles
and wires.
regards

**Comment by martinfleis** [comment]
> Is there any particular reason why you don't consider Point geoms as an input as well? Am I missing something?

It is a different use case. The purpose of this function is to facilitate the conversion if you don't have data representing nodes. Because if you do, there's no need for it, you can build the Graph directly with networkx Graph builders.

**Pull request closed without merging**
