### PR TITLE
GHA: update actions

### PR DESCRIPTION
**Pull request by martinfleis**
@jGaboardi how do I make dependabot to do this?

### CODE REVIEW

**Comment by jGaboardi** [comment]
In `spaghetti`, `spopt`, etc. we have a [`.github/dependabot.yml`](https://github.com/pysal/spaghetti/blob/main/.github/dependabot.yml). However, the link for configuration help in the top comments[^1] does not appear to work anymore (or at least right now). And come to think of it, I haven't seen any `dependabot` requests recently. 

[^1]: https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

**Comment by jGaboardi** [comment]
This link seems to be what we are looking for: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates

**Comment by jGaboardi** [comment]
As far I understand, the versioning will be checked (e.g. `actions/setup-python`), but something like `mamba-org/provision-with-micromamba` --> `mamba-org/setup-micromamba` will not be picked up.

**Comment by jGaboardi** [comment]
And we also have to [turn it on](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates).

**Comment by martinfleis** [comment]
> As far I understand, the versioning will be checked (e.g. actions/setup-python), but something like mamba-org/provision-with-micromamba --> mamba-org/setup-micromamba will not be picked up.

I'm aware. 

On this note, I have noticed that `actions/create-release` and `actions/upload-release-asset` are both archived, so we should maybe look for another solution. We did something else recently in pyogrio, so might be worth checking that. But not in this PR.

**Review by jGaboardi — APPROVED** [review]

**Pull request merged**
