### PR TITLE
Add pyproject.toml file

### LINKED ISSUE #415: add a project.toml?
Should we add a `project.toml` file to complement our current `setup.py` and [`setup.cfg`](https://github.com/pysal/momepy/blob/main/setup.cfg)?

https://github.com/pysal/momepy/blob/e836a503c8b58d6309fc74bd2b143c5e284fb55b/setup.py#L1

### PR DESCRIPTION
**Pull request by jGaboardi**
Resolves #415 and based on https://github.com/geopandas/geopandas/pull/2419, and https://github.com/geopandas/geopandas/pull/2512.

Still may need to work out the kinks later. First time trying this.

### CODE REVIEW

**Comment by martinfleis** [comment]
Is it possible to remove setup.cfg and use only setup.py to deal with versioneer and pyproject?

**Comment by martinfleis** [comment]
versioneer should be fine with specs in pyproject.toml instead of setup.cfg - https://github.com/python-versioneer/python-versioneer/blob/master/INSTALL.md#common-steps

**Comment by jGaboardi** [comment]
Seems this is a bit more complicated for `flake8` and may require another package: [`pyproject-flake8`](https://github.com/csachs/pyproject-flake8).

**Comment by jGaboardi** [comment]
@martinfleis Welp... I am not sure how to proceed with this... Should we just keep the stuff in `setup.cfg` for now?

**Comment by jGaboardi** [comment]
Adding `"versioneer[toml]==0.26"` seems to resolve the build for testing environments (see [here](https://github.com/python-versioneer/python-versioneer/issues/338#issuecomment-1250131403)), but not for doc building.

**Comment by martinfleis** [comment]
Just leave cfg as it id then.

**Review by martinfleis — APPROVED** [review]
I guess we can merge this.

**Pull request merged**
