### PR TITLE
DOC: compat with latest sphinx pydata theme

### LINKED ISSUE #362: DOC: broken colours with new pydata_sphinx_theme
We are overriding colours from `pydata_sphinx_theme` and it seems that since the latest version released yesterday, we need to do it differently (and make it work with both light and dark schemes). Compare yourself:

- expected: http://docs.momepy.org/en/stable/ 
- now: http://docs.momepy.org/en/latest/

### PR DESCRIPTION
**Pull request by martinfleis**
Closes #362

### CODE REVIEW

**Comment by martinfleis** [comment]
Here's the result https://momepy--373.org.readthedocs.build/en/373/index.html . The logo is not suited for the dark theme but I can only fix the one in the header. Not sure how to fix the one on homepage.

**Comment by jGaboardi** [comment]
> Here's the result https://momepy--373.org.readthedocs.build/en/373/index.html . The logo is not suited for the dark theme but I can only fix the one in the header. Not sure how to fix the one on homepage.

Yeah, that new dark theme is looking nice. All except the logo, seems like.

**Comment by martinfleis** [comment]
https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/light-dark.html#use-theme-dependent-content

This will solve the homepage image.

**Comment by jGaboardi** [comment]
@martinfleis Will that be added to this PR or another one?

**Comment by martinfleis** [comment]
Here, give me a couple of mins

**Comment by martinfleis** [comment]
ready now

**Comment by jGaboardi** [comment]
New one looking nice! Do we need to wait for the new round of CI to pass or are we good to merge now?

**Review by jGaboardi — APPROVED** [review]

**Pull request merged**
