### PR TITLE
resolve iteritems() warnings and others

### LINKED ISSUE #435: update .iteritems() to  .items()
Following a fresh crop of [`FutureWarning`](https://github.com/pysal/momepy/actions/runs/3193784898/jobs/5212703550#step:6:170)s, we should update a handful of lines of code from `.iteritems()` to  `.items()`.

### PR DESCRIPTION
**Pull request by jGaboardi**
Resolves #435.

Also:
* [`UserWarning: Boolean Series key will be reindexed to match DataFrame index.`](https://github.com/pysal/momepy/actions/runs/3193784898/jobs/5212703675#step:6:265)
* [`DeprecationWarning: In the next version of libpysal, ...`](https://github.com/pysal/momepy/actions/runs/3193784898/jobs/5212703675#step:6:218)

### CODE REVIEW

**Comment by martinfleis** [comment]
`38-minimal.yaml` should not fail (main does not). Can you look into that?

**Comment by jGaboardi** [comment]
> `38-minimal.yaml` should not fail (main does not). Can you look into that?

Yep, that was my oversight.

The issue is with including the `drop_islands` keyword argument in [`W.to_adjlist()`](https://github.com/pysal/momepy/actions/runs/3212599779/jobs/5251608146#step:6:166), which was introduced in [`libpysal=4.6.0`](https://github.com/pysal/libpysal/blob/v4.6.0/libpysal/weights/weights.py#L278). So, we either need to (1) make the decision for pushing the minimally supported test from [`libpysal=4.2.2`](https://github.com/pysal/momepy/actions/runs/3212599779/jobs/5251608146#step:5:136), as is stipulated in [`38-minimal.yaml`](https://github.com/pysal/momepy/blob/main/ci/envs/38-minimal.yaml#L8) , or (2) add in a `libpysal` version checker that flags `libpysal<4.6.0` and doesn't pass in the `drop_islands` keyword argument.

I vote for solution (1), but will defer to your opinion.

**Comment by martinfleis** [comment]
I'm fine with depending on the latest versions of pysal modules as we have a control over those.

**Comment by martinfleis** [comment]
Thanks again!

**Pull request merged**
